class Autogenerated {
  Autogenerated({
      List<Data>? data,}){
    _data = data;
}

  Autogenerated.fromJson(dynamic json) {
    if (json['data'] != null) {
      _data = [];
      json['data'].forEach((v) {
        _data?.add(Data.fromJson(v));
      });
    }
  }
  List<Data>? _data;

  List<Data>? get data => _data;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (_data != null) {
      map['data'] = _data?.map((v) => v.toJson()).toList();
    }
    return map;
  }

}

class Data {
  Data({
      Entry? entry, 
      String? url, 
      num? votes,}){
    _entry = entry;
    _url = url;
    _votes = votes;
}

  Data.fromJson(dynamic json) {
    _entry = json['entry'] != null ? Entry.fromJson(json['entry']) : null;
    _url = json['url'];
    _votes = json['votes'];
  }
  Entry? _entry;
  String? _url;
  num? _votes;

  Entry? get entry => _entry;
  String? get url => _url;
  num? get votes => _votes;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (_entry != null) {
      map['entry'] = _entry?.toJson();
    }
    map['url'] = _url;
    map['votes'] = _votes;
    return map;
  }

}

class Entry {
  Entry({
      num? malId, 
      String? url, 
      Images? images, 
      String? title,}){
    _malId = malId;
    _url = url;
    _images = images;
    _title = title;
}

  Entry.fromJson(dynamic json) {
    _malId = json['mal_id'];
    _url = json['url'];
    _images = json['images'] != null ? Images.fromJson(json['images']) : null;
    _title = json['title'];
  }
  num? _malId;
  String? _url;
  Images? _images;
  String? _title;

  num? get malId => _malId;
  String? get url => _url;
  Images? get images => _images;
  String? get title => _title;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['mal_id'] = _malId;
    map['url'] = _url;
    if (_images != null) {
      map['images'] = _images?.toJson();
    }
    map['title'] = _title;
    return map;
  }

}

class Images {
  Images({
      Jpg? jpg, 
      Webp? webp,}){
    _jpg = jpg;
    _webp = webp;
}

  Images.fromJson(dynamic json) {
    _jpg = json['jpg'] != null ? Jpg.fromJson(json['jpg']) : null;
    _webp = json['webp'] != null ? Webp.fromJson(json['webp']) : null;
  }
  Jpg? _jpg;
  Webp? _webp;

  Jpg? get jpg => _jpg;
  Webp? get webp => _webp;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (_jpg != null) {
      map['jpg'] = _jpg?.toJson();
    }
    if (_webp != null) {
      map['webp'] = _webp?.toJson();
    }
    return map;
  }

}

class Webp {
  Webp({
      String? imageUrl, 
      String? smallImageUrl, 
      String? largeImageUrl,}){
    _imageUrl = imageUrl;
    _smallImageUrl = smallImageUrl;
    _largeImageUrl = largeImageUrl;
}

  Webp.fromJson(dynamic json) {
    _imageUrl = json['image_url'];
    _smallImageUrl = json['small_image_url'];
    _largeImageUrl = json['large_image_url'];
  }
  String? _imageUrl;
  String? _smallImageUrl;
  String? _largeImageUrl;

  String? get imageUrl => _imageUrl;
  String? get smallImageUrl => _smallImageUrl;
  String? get largeImageUrl => _largeImageUrl;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['image_url'] = _imageUrl;
    map['small_image_url'] = _smallImageUrl;
    map['large_image_url'] = _largeImageUrl;
    return map;
  }

}

class Jpg {
  Jpg({
      String? imageUrl, 
      String? smallImageUrl, 
      String? largeImageUrl,}){
    _imageUrl = imageUrl;
    _smallImageUrl = smallImageUrl;
    _largeImageUrl = largeImageUrl;
}

  Jpg.fromJson(dynamic json) {
    _imageUrl = json['image_url'];
    _smallImageUrl = json['small_image_url'];
    _largeImageUrl = json['large_image_url'];
  }
  String? _imageUrl;
  String? _smallImageUrl;
  String? _largeImageUrl;

  String? get imageUrl => _imageUrl;
  String? get smallImageUrl => _smallImageUrl;
  String? get largeImageUrl => _largeImageUrl;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['image_url'] = _imageUrl;
    map['small_image_url'] = _smallImageUrl;
    map['large_image_url'] = _largeImageUrl;
    return map;
  }

}