import 'package:animelist/Models/SearchedModel.dart';
import 'package:animelist/Models/TrendingModel.dart';
import 'package:velocity_x/velocity_x.dart';

class MyStore extends VxStore {
  late Autogenerated1 trendingModel;
  late SearchedModel searchedModel;
  MyStore(){
    trendingModel = Autogenerated1();
    searchedModel = SearchedModel();
  }
}